### ISSUE TITLE
Is there a .klc file?

### ISSUE THREAD

**Issue by 7fe** [hxp-plus/hxp-dvorak-windows#1]

**Comment by hxp-plus** [comment]
You may use Microsoft Keyboard Layout Creator to create your own dlls if you are not satisfied with the original programmer dvorak layout. However, I think the original one is good enough.
But, Microsoft Keyboard Layout Creator, as well as the programmer dvorak layout installer `kbddvp-1_2_7-i386.exe`, cannot change the modifier keys such as `Ctrl` `CapsLock`, etc.
A safer way to change modifier keys is to use `AutoHotKey`. You may also change (or add if the key doesn't exist) the value of key `Scancode Map` in `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Keyboard Layout` if you don't want to install `AutoHotKey` or let it autostart.
